name: fuzzy
on: push
concurrency:
  # Cancel other jobs in the same branch. We don't care whether CI passes
  # on old commits.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
env:
  MODIN_GITHUB_CI: 'true'
  PIP_INDEX_URL: https://us-central1-waleko-personal.cloudfunctions.net/pypiWayback/2024-01-10
  UV_INDEX_URL: https://us-central1-waleko-personal.cloudfunctions.net/pypiWayback/2024-01-10

jobs:
  test-fuzzydata:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.9']
        engine: [ray, dask]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/mamba-env
      with:
        environment-file: environment-dev.yml
        python-version: ${{matrix.python-version}}
    - name: test-fuzzydata (engine ${{matrix.engine}}, python ${{matrix.python-version}})
      run: python -m pytest modin/experimental/fuzzydata/test/test_fuzzydata.py -Wignore::UserWarning
        --log-file=/tmp/fuzzydata-test-wf-${{matrix.engine}}/run.log --log-file-level=INFO
      env:
        MODIN_ENGINE: ${{matrix.engine}}
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: fuzzydata-test-workflow-${{matrix.engine}}
        path: /tmp/fuzzydata-test-wf-${{matrix.engine}}/*    # Must match output dir in test_fuzzydata.py
        if-no-files-found: error
